const ADD_POST_REQUSET = 'ADD_POST_REQUSET'
const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS'
const ADD_POST_FAILURE = 'ADD_POST_FAILURE'

const ADD_COMMENT_REQUSET = 'ADD_COMMENT_REQUSET'
const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS'
const ADD_COMMENT_FAILURE = 'ADD_COMMENT_FAILURE'